### ISSUE TITLE
Question: How to style blocks themselves?

### ISSUE THREAD

**Issue by bradymwilliams** [jakesgordon/javascript-tetris#3]
How would you go about adding background images instead of plain colors to the blocks?

**Comment by luciopanepinto** [comment]
For example, for the piece1, i would place attribute for each part of the piece : piece1[part=1], piece1[part=2], piece1[part=3], etc. And for each part, i make a style in the CSS for attach the appropriate background to draw the piece with all images.

**Comment by RAIDEND01** [comment]
I think for the piece1, i would place attribute for each part of the piece : piece1[part=1], piece1[part=2], piece1[part=3], etc. And for each part, i make a style in the CSS for attach the appropriate background to draw the piece with all images.
