### ISSUE TITLE
Code Obfuscation

### ISSUE THREAD

**Issue by osamu-kj** [jakesgordon/javascript-tetris#42]
just the fact that you've obfuscated the code makes me wanna kms rn
there was no need to obfuscate it & make it10 times harder to understand.

**Comment by directonlijn** [comment]
The code in the index.html isn't obfuscated right? Only the stats.js which has a clear reference to another github repo?

**Comment by osamu-kj** [comment]
oh i see didnt take too much time to understand to code (in fact.. couple mins) therefore i apologise for that one..
